title: scuola di pensiero
remote_theme: https://github.com/poole/lanyon?ref=jekyll-themes.com

search_enabled: true
auto_page_title: true

sidebar:
  - label: altre pagine
    children:
      - pagina12
      - pagina12
  - pagina12

