title: scuola di pensiero
remote_theme: zendesk/jekyll-theme-zendesk-garden@main 


baseurl: /mywebsite

search_enabled: true
auto_page_title: true

sidebar:
  - home
  - label: altre pagine
    children:
      - pagina12
  - pagina12

