title: scuola di pensiero
remote_theme: poole/lanyon@master

search_enabled: true
auto_page_title: true

sidebar:
  - label: altre pagine
    children:
      - pagina12
      - pagina12
  - pagina12

