title: scuola di pensiero
remote_theme: zendesk/jekyll-theme-zendesk-garden@main 

search_enabled: false
auto_page_title: true

sidebar:
  - label: altre pagine
    children:
      - pagina12
      - pagina12
  - pagina12

