title: scuola di pensiero
remote_theme: remote_theme: abhinavs/moonwalk

search_enabled: true
auto_page_title: true

sidebar:
  - label: altre pagine
    children:
      - pagina12
      - pagina12
  - pagina12

